/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.apache.pdfbox.Loader;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;

/**
 *
 * @author luisd
 */
public class MenuDeAyuda extends javax.swing.JInternalFrame {

    /**
     * Creates new form CargarVehiculo
     */
    public MenuDeAyuda() {
        initComponents();
        mostrarPDFEnPanel();
    }

    private void mostrarPDFEnPanel() {
        try {
            String rutaProyecto = System.getProperty("user.dir");
            String rutaPDF = rutaProyecto + "\\src\\Imagen\\Manual_de_Usuario.pdf";
            File archivo = new File(rutaPDF);

            if (!archivo.exists()) {
                JOptionPane.showMessageDialog(this, "No se encontró el archivo PDF:\n" + rutaPDF);
                return;
            }

            try (PDDocument document = Loader.loadPDF(archivo)) {
                PDFRenderer pdfRenderer = new PDFRenderer(document);

                JPanel panelContenedor = new JPanel();
                panelContenedor.setLayout(new BoxLayout(panelContenedor, BoxLayout.Y_AXIS));

                for (int i = 0; i < document.getNumberOfPages(); i++) {
                    BufferedImage imagen = pdfRenderer.renderImageWithDPI(i, 100);
                    JLabel paginaLabel = new JLabel(new ImageIcon(imagen));
                    paginaLabel.setBorder(BorderFactory.createEmptyBorder(10, 0, 10, 0));
                    panelContenedor.add(paginaLabel);
                }

                JScrollPane scroll = new JScrollPane(panelContenedor);
                scroll.setPreferredSize(new Dimension(650, 400));

                PanelInfo.setLayout(new BorderLayout());
                PanelInfo.add(scroll, BorderLayout.CENTER);
                PanelInfo.revalidate();
                PanelInfo.repaint();

                System.out.println("✅ Manual mostrado correctamente dentro del panel.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al mostrar el PDF:\n" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInfo = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Menu de ayuda");

        javax.swing.GroupLayout PanelInfoLayout = new javax.swing.GroupLayout(PanelInfo);
        PanelInfo.setLayout(PanelInfoLayout);
        PanelInfoLayout.setHorizontalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        PanelInfoLayout.setVerticalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInfo;
    // End of variables declaration//GEN-END:variables
}
