/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import Configuracion.GraficaDiagrama;
import java.awt.Container;
import java.awt.Graphics2D;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author luisd
 */
public class Diagrama extends javax.swing.JPanel {

    private List<String> listaCadenas;
    private int indiceCadenaActual;
    private int indicePosicionCadena = 0;

    /**
     * Creates new form Diagrama
     */
    public Diagrama() {
        initComponents();
    }

    public int getIndicePosicionCadena() {
        return indicePosicionCadena;
    }

    public GraficaDiagrama getGraficaDiagrama() {
        // Este método debe retornar la instancia de GraficaDiagrama asociada
        // Ajusta según cómo tengas implementada tu clase Diagrama
        Container parent = getParent();
        while (parent != null) {
            if (parent instanceof GraficaDiagrama) {
                return (GraficaDiagrama) parent;
            }
            parent = parent.getParent();
        }
        return null;
    }
    // En la clase Diagrama
    private boolean cadenaTerminada = false;

    public boolean isCadenaTerminada() {
        return cadenaTerminada;
    }

    public void setCadenaTerminada(boolean cadenaTerminada) {
        this.cadenaTerminada = cadenaTerminada;
    }

    public void setIndicePosicionCadena(int indice) {
        this.indicePosicionCadena = indice;
    }

    public void setListaCadenas(List<String> listaCadenas) {
        this.listaCadenas = listaCadenas;
    }

    public List<String> getListaCadenas() {
        return listaCadenas;
    }

    public void setIndiceCadenaActual(int indice) {
        this.indiceCadenaActual = indice;
    }

    public int getIndiceCadenaActual() {
        return indiceCadenaActual;
    }

    // ✅ Métodos getter existentes
    public javax.swing.JTable getTblCadenas() {
        return TblCadenas;
    }

    public javax.swing.JTable getTblVisualizar() {
        return TblVisualizar;
    }

    public javax.swing.JTextField getTxtVisualizarCadenda() {
        return TxtVisualizarCadenda;
    }

    // ✅ Nuevos métodos getter para acceder a más componentes
    public javax.swing.JPanel getMiniDiagrama() {
        return MiniDiagrama;
    }

    public javax.swing.JButton getBtnAnterior() {
        return BtnAnterior;
    }

    public javax.swing.JButton getBtnSiguiente() {
        return BtnSiguiente;
    }

    public javax.swing.JButton getBtnCambiarCadena() {
        return BtnCambiarCadena;
    }

    public javax.swing.JButton getBtnRegresaCadena() {
        return BtnRegresaCadena;
    }

    // ✅ Método para limpiar el mini diagrama (útil para redibujar)
    public void limpiarMiniDiagrama() {
        MiniDiagrama.removeAll();
        MiniDiagrama.repaint();
    }

    // ✅ Método para obtener el Graphics del mini diagrama para dibujar
    public Graphics2D getGraphicsMiniDiagrama() {
        return (Graphics2D) MiniDiagrama.getGraphics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MiniDiagrama = new javax.swing.JPanel();
        BtnAnterior = new javax.swing.JButton();
        BtnSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblCadenas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblVisualizar = new javax.swing.JTable();
        BtnCambiarCadena = new javax.swing.JButton();
        BtnRegresaCadena = new javax.swing.JButton();
        TxtVisualizarCadenda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnResultado = new javax.swing.JButton();

        MiniDiagrama.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout MiniDiagramaLayout = new javax.swing.GroupLayout(MiniDiagrama);
        MiniDiagrama.setLayout(MiniDiagramaLayout);
        MiniDiagramaLayout.setHorizontalGroup(
            MiniDiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        MiniDiagramaLayout.setVerticalGroup(
            MiniDiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        BtnAnterior.setText("Anterior");
        BtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorActionPerformed(evt);
            }
        });

        BtnSiguiente.setText("Siguiente");
        BtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteActionPerformed(evt);
            }
        });

        TblCadenas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Listado:", "Cadenas:", "Estado:", "Resultado:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblCadenas);

        TblVisualizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane3.setViewportView(TblVisualizar);

        BtnCambiarCadena.setText("Cambiar Cadena");
        BtnCambiarCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCambiarCadenaActionPerformed(evt);
            }
        });

        BtnRegresaCadena.setText("Regresar Cadena");
        BtnRegresaCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresaCadenaActionPerformed(evt);
            }
        });

        TxtVisualizarCadenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtVisualizarCadendaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("Cadena a analizar:");

        BtnResultado.setText("Resultado");
        BtnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MiniDiagrama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnRegresaCadena)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnCambiarCadena)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnSiguiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnResultado)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtVisualizarCadenda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MiniDiagrama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnAnterior)
                            .addComponent(BtnSiguiente)
                            .addComponent(BtnResultado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnRegresaCadena)
                            .addComponent(BtnCambiarCadena))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtVisualizarCadenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtVisualizarCadendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtVisualizarCadendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtVisualizarCadendaActionPerformed

    private void BtnCambiarCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCambiarCadenaActionPerformed
        // TODO add your handling code here:
        GraficaDiagrama.cambiarCadena(this);
    }//GEN-LAST:event_BtnCambiarCadenaActionPerformed

    private void BtnRegresaCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresaCadenaActionPerformed
        // TODO add your handling code here:
        GraficaDiagrama.regresarCadena(this);
    }//GEN-LAST:event_BtnRegresaCadenaActionPerformed

    private void BtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorActionPerformed
        // TODO add your handling code here:
        GraficaDiagrama.moverAutomata(this, false);
    }//GEN-LAST:event_BtnAnteriorActionPerformed

    private void BtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteActionPerformed
        // TODO add your handling code here:
        GraficaDiagrama.moverAutomata(this, true);
    }//GEN-LAST:event_BtnSiguienteActionPerformed

    private void BtnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResultadoActionPerformed
        // TODO add your handling code here:
        GraficaDiagrama.procesarTodasLasCadenas(this);
    }//GEN-LAST:event_BtnResultadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnCambiarCadena;
    private javax.swing.JButton BtnRegresaCadena;
    private javax.swing.JButton BtnResultado;
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JPanel MiniDiagrama;
    private javax.swing.JTable TblCadenas;
    private javax.swing.JTable TblVisualizar;
    private javax.swing.JTextField TxtVisualizarCadenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
