/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Configuracion.Abrir;
import Configuracion.Ejemplos;
import Configuracion.Guardar;
import Configuracion.Nuevo;
import Configuracion.PanelLateral;
import javax.swing.*;
import java.io.File;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author luisd
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private Guardar gestorGuardado;
    private JDesktopPane escritorio;
    private Map<JInternalFrame, File> archivosPorFrame = new HashMap<>();
    private Map<JInternalFrame, JTextArea> areasTextoPorFrame = new HashMap<>();
    private PanelConfi panelConfi;

    /**
     * Creates new form Menu
     */
    public MenuPrincipal() {
        initComponents();
        Escritorio.setLayout(null);
        gestorGuardado = new Guardar(Escritorio);
        this.escritorio = Escritorio;
        // Crear el panel de configuración
        panelConfi = new PanelConfi();
        configurarEjemplos();
    }

    public void registrarHoja(JInternalFrame frame, JTextArea textArea, File archivo) {
        archivosPorFrame.put(frame, archivo);
        areasTextoPorFrame.put(frame, textArea);

        frame.addInternalFrameListener(new javax.swing.event.InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                archivosPorFrame.remove(frame);
                areasTextoPorFrame.remove(frame);
            }
        });

        frame.setTitle(archivo.getName());
        frame.setToolTipText(archivo.getAbsolutePath());
    }
    // En tu método que crea el menú principal

    // ✅ MÉTODO NUEVO: Configurar los ejemplos manualmente
    private void configurarEjemplos() {
        jMenuItem1.addActionListener(e -> Ejemplos.cargarEjemplo(0, Escritorio));
        jMenuItem2.addActionListener(e -> Ejemplos.cargarEjemplo(1, Escritorio));
        jMenuItem3.addActionListener(e -> Ejemplos.cargarEjemplo(2, Escritorio));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Nuevo = new javax.swing.JMenu();
        AbrirMenu = new javax.swing.JMenuItem();
        GuardarMenu = new javax.swing.JMenuItem();
        GuardarComoMenu = new javax.swing.JMenuItem();
        Nuevomenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opCargarVehiculo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(new java.awt.Color(204, 204, 204));
        Escritorio.setMinimumSize(new java.awt.Dimension(1100, 580));
        Escritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        Escritorio.getAccessibleContext().setAccessibleName("");

        Nuevo.setText("Archivo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        AbrirMenu.setIcon(new javax.swing.ImageIcon("D:\\Descargas\\icons8-documento-20.png")); // NOI18N
        AbrirMenu.setText("Abrir");
        AbrirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirMenuActionPerformed(evt);
            }
        });
        Nuevo.add(AbrirMenu);

        GuardarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        GuardarMenu.setIcon(new javax.swing.ImageIcon("D:\\Descargas\\disk_2493389.png")); // NOI18N
        GuardarMenu.setText("Guardar");
        GuardarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarMenuActionPerformed(evt);
            }
        });
        Nuevo.add(GuardarMenu);

        GuardarComoMenu.setIcon(new javax.swing.ImageIcon("D:\\Descargas\\folder_15459380.png")); // NOI18N
        GuardarComoMenu.setText("Guardar Como");
        GuardarComoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarComoMenuActionPerformed(evt);
            }
        });
        Nuevo.add(GuardarComoMenu);

        Nuevomenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Nuevomenu.setIcon(new javax.swing.ImageIcon("D:\\Descargas\\file_788859.png")); // NOI18N
        Nuevomenu.setText("Nuevo");
        Nuevomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevomenuActionPerformed(evt);
            }
        });
        Nuevo.add(Nuevomenu);

        jMenuBar1.add(Nuevo);

        jMenu2.setText("Help");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        opCargarVehiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        opCargarVehiculo.setIcon(new javax.swing.ImageIcon("D:\\Descargas\\help_2762512.png")); // NOI18N
        opCargarVehiculo.setText("Menu ayuda");
        opCargarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCargarVehiculoActionPerformed(evt);
            }
        });
        jMenu2.add(opCargarVehiculo);

        jMenu1.setText("Ejemplos");

        jMenuItem1.setText("Ejemplo 1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Ejemplo 2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Ejemplo 3");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu2.add(jMenu1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void opCargarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCargarVehiculoActionPerformed
        MenuDeAyuda verventana = new MenuDeAyuda();
        Escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_opCargarVehiculoActionPerformed

    private void NuevomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevomenuActionPerformed
        new Nuevo().crearNuevaHoja(Escritorio);
    }//GEN-LAST:event_NuevomenuActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        new Guardar(Escritorio).guardarComo();
    }//GEN-LAST:event_NuevoActionPerformed

    private void GuardarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarMenuActionPerformed
        gestorGuardado.guardarHoja();
    }//GEN-LAST:event_GuardarMenuActionPerformed

    private void GuardarComoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarComoMenuActionPerformed
        gestorGuardado.guardarComo();
    }//GEN-LAST:event_GuardarComoMenuActionPerformed

    private void AbrirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirMenuActionPerformed
        PanelLateral.mostrar(Escritorio);

        // Obtener la referencia del panel de configuración que ya está visible
        PanelConfi panelConfiguracion = PanelLateral.getPanelConfi();

        if (panelConfiguracion != null) {
            Abrir gestorAbrir = new Abrir(Escritorio, this, panelConfiguracion);
            gestorAbrir.abrirArchivo();
        } else {
            JOptionPane.showMessageDialog(this, "Error: No se pudo acceder al panel de configuración");
        }
    }//GEN-LAST:event_AbrirMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirMenu;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem GuardarComoMenu;
    private javax.swing.JMenuItem GuardarMenu;
    private javax.swing.JMenu Nuevo;
    private javax.swing.JMenuItem Nuevomenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem opCargarVehiculo;
    // End of variables declaration//GEN-END:variables
}
